lidar:
  - driver:
      udp_port: 2368                   #UDP port of lidar
      ptc_port: 9347                   #PTC port of lidar
      device_ip_address: 192.168.1.11 #host_ip_address
      pcap_play_synchronization: true  # pcap play rate synchronize with the host time     
      pcap_path: "Your pcap file path" #The path of pcap file
      correction_file_path: "/home/me/ros2pi-swz/QT128_Angle_Correction_File.csv" #The path of correction file
      firetimes_path: "/home/me/ros2pi-swz/QT128_Firetime_Correction_File.csv" #The path of firetimes file
      source_type: 1                   #The type of data source, 1: real-time lidar connection, 2: pcap, 3: packet rosbag    
      #transform param
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
    ros:
      ros_frame_id: hesai_lidar                      #Frame id of packet message and point cloud message
      ros_recv_packet_topic: /lidar_packets         #Topic used to receive lidar packets from rosbag
      ros_send_packet_topic: /lidar_packets         #Topic used to send lidar raw packets through ROS
      ros_send_point_cloud_topic: /lidar/points     #Topic used to send point cloud through ROS
      send_packet_ros: true                          #true: Send packets through ROS 
      send_point_cloud_ros: true                     #true: Send point cloud through ROS    
